name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install and build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Lint and test
        run: |
          pnpm lint
          pnpm test
