name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - id: release
        uses: gzzhanghao/pnpm-workspace-release-action@v1.0
        with:
          latest: ${{ github.event.ref == 'refs/heads/main' }}

      - if: ${{ steps.release.outputs.release_created }}
        run: pnpm install --frozen-lockfile

      - if: ${{ steps.release.outputs.release_created }}
        run: pnpm build

      - if: ${{ steps.release.outputs.release_created }}
        run: pnpm publish -r
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
